### ISSUE TITLE
theonionbox on freebsd

### ISSUE THREAD

**Issue by senovr** [ralphwetzel/theonionbox#19]
Hi, 
I am running tor node on the freebsd server.
I tried your extension, and suprisingly (for me) it still works on BSD.
The only thing i curretly stuck on is making it running as a daemon or start automatically during FreeBSD boot.
Can you give some hints, or ( preferrably) update the wiki ?

**Comment by ralphwetzel** [comment]
Hi!
Thanks for that feedback.
I'm about to set up a FreeBSD server to test the Box & create the necessary scripts to start it automatically. Might yet need some time to be finished.
Best regards, Ralph

**Comment by ralphwetzel** [comment]
Hi @senovr!
I've just released [v3.1](https://github.com/ralphwetzel/theonionbox/releases/tag/v3.1) of The Box that should bring everything you need to run it as a service on FreeBSD. You may as well check the dedicated [wiki page](https://github.com/ralphwetzel/theonionbox/wiki/HowTo:-Run-The-Onion-Box-as-a-background-service-on-FreeBSD) for further details of how to set this up.
I would be happy to get a feedback if you gave it a try - good or bad!

Best regards,
Ralph

**Comment by senovr** [comment]
Hi Ralph,

tried your script, works for me.
Few difficulties I have to go through:

1. Python-related. lang/python need to be installed for symlink to work
correctly.
pkg install lang/python.

2. tzsetup For some reasons there is an error, requiring correct timezone.

nas4free FreeBSD/ root^> ./theonionbox.sh start
nas4free FreeBSD/ root^> Traceback (most recent call last):
  File "/home/theonionbox/theonionbox/theonionbox.py", line 1583, in
<module>
    box_cron.add_job(job_NewDayNotification, 'cron', id='ndn', hour='0',
minute='0', second='0')
  File "/usr/home/theonionbox/theonionbox/tob/scheduler.py", line 41, in
add_job
    return self.schedulr.add_job(func, trigger, id=id, args=args,
kwargs=kwargs, **trigger_args)
  File
"/usr/local/lib/python2.7/site-packages/apscheduler/schedulers/base.py",
line 411, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File
"/usr/local/lib/python2.7/site-packages/apscheduler/schedulers/base.py",
line 905, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File
"/usr/local/lib/python2.7/site-packages/apscheduler/schedulers/base.py",
line 890, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File
"/usr/local/lib/python2.7/site-packages/apscheduler/triggers/cron/__init__.py",
line 50, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/local/lib/python2.7/site-packages/apscheduler/util.py", line
83, in astimezone
    'Unable to determine the name of the local timezone -- you must
explicitly '
ValueError: Unable to determine the name of the local timezone -- you must
explicitly specify the name of the local timezone. Please refrain from
using timezones like EST to prevent problems with daylight saving time.
Instead, use a locale based timezone name (such as Europe/Helsinki).


After running tzsetup and pointing the freebsd to correct tz- all working
like charm.

Thank you very much!
Sergey.

p.s.

one question, just because of curuoisty-
in the tor network section, it seems that theonionbox can not reach
onionnooo data ( pls see below).
Am i need to change something in tor or theonionbox config files to make
this work?


Network Status
No Onionoo Network data to display. Reload page to update...

2016-11-27 3:55 GMT+07:00 ralphwetzel <notifications@github.com>:

**Comment by ralphwetzel** [comment]
Hi Sergey!

Thanks for your feedback & the great info that you are able to run The Box on FreeBSD.
To compensate for the timezone issue you discovered I added a check that ensures that tz is adequately set or the operator gets a message to run tzsetup.
The notice you see regarding 'Onionoo Network data' doesn't harm. It's related to the fact that it takes some time to read this data & process it - which is done as a background job. After you reloaded the page (hit F5 once or more as being told) you should get a display of the data - if there is data available from the onionoo servers.

Best regards & thanks again for using The Onion Box,

Ralph
