### ISSUE TITLE
Unable to reach theonionbox via https with ssl enabled

### ISSUE THREAD

**Issue by skyYaga** [ralphwetzel/theonionbox#22]
Hi there,

I configured theonionbox (v3.1) on FreeBSD with a valid certificate from letsencrypt.

ssl = yes
ssl_certificate = /path/to/cert.pem
ssl_key = /path/to/privkey.pem

The cert and privkey are readable for the user that is running theonionbox.

The log says: "Operating with WSGIserver in SSL mode!"

But I'm unable to reach theonionbox via https. It's just reachable via http under its configured address/port.

Do you have seen an issue like that before?

Yaga

**Comment by ralphwetzel** [comment]
Hi @skyYaga!
I have to confirm that SSL support is broken if operating with WSGIserver (introduced with v3.0) and has some issues even when operating with CherryPy.
Those issues should be fixed now. Please use the latest (Pre)Release ([v3.2RC2](https://github.com/ralphwetzel/theonionbox/releases/tag/v3.2RC2)) to test SSL support with your configuration. 
Thanks again for your feedback!

Ralph

**Comment by skyYaga** [comment]
Hi @ralphwetzel!

Thanks, with v3.2RC2 it's working!

Yaga
