### ISSUE TITLE
Stopped working after couple days

### ISSUE THREAD

**Issue by redmanmale** [ralphwetzel/theonionbox#26]
I set up TheOnionBox and it was working for a couple days. I changed only control port in config.
After that I tried to check up my node and interface just hangs on login page and after several minutes returns `Error: 500 Internal Server Error` and stops working.

Here's [log](https://gist.github.com/redmanmale/d0fcc46f65a05a508793ff7b3fd00acf) from start to crash.
I only removed my node's fingerpring from log.

Any help would be appreciated.

**Env**
Windows 8.1 x64, Python 3.6.1, TheOnionBox 3.2.1.

Update.
After couple reboots it's working again.
What could cause such unstable behaviour?

**Comment by ralphwetzel** [comment]
Hi!
Thank you for your feedback. Are you able to reproduce that error?
Additional comment: 9151 is the (standard) ControlPort of TorBrowser.
Are you sure this setting is by intension?
Best regards, Ralph

**Comment by redmanmale** [comment]
Thanks for replying!

It's happening from time to time, but I cound not figure out concrete steps to reproduce yet.
According to Tor man, standart control port is 9051, but I use 9151. I set it in the Tor config and in the OnionBox config.
