### ISSUE TITLE
Add a link to the project page

### ISSUE THREAD

**Issue by alainwolf** [ralphwetzel/theonionbox#30]
On the page you have a kinds of links to the Tor Project, MIT, font source etc. But no link to your project itself. "The Onion Box" is mentioned three times on the page, none are linked. So I start a search on DDG and get all kind of Onion stuff, but not your project. I search on GitHub for "The Onion Box" and it says "We couldn’t find any repositories matching 'the onion box' ". One has to search for "theonionbox" which is mentioned nowhere on the page.

**Comment by ralphwetzel** [comment]
That‘s a great finding! You‘re absolutely right! I‘ll „fix“ this definitely.
R.
