### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by ronnicek** [ralphwetzel/theonionbox#37]
Hi,

I am running tor relay in Tor in Docker. Does anyone have Dockerfile for theonionbox? If not, I will try to check it, but dont know when I will time for it.. but what I saw, it should not be so hard :)

**Comment by ralphwetzel** [comment]
It's done: There's a Dockerfile available now in the [Docker](https://github.com/ralphwetzel/theonionbox/blob/master/Docker) directory.
