### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by xandr0s** [ralphwetzel/theonionbox#46]
I started theonionbox and watched the load increase a long time (~month). After stop service the load has disappeared. If restarted - the load is negligible. Now I added in cron restart each night
![2018-04-18 15-25-45](https://user-images.githubusercontent.com/1709302/38920464-859a8d12-431d-11e8-8e58-aa42412e293d.png)
![2018-04-18 15-25-33](https://user-images.githubusercontent.com/1709302/38920465-85bfa8e0-431d-11e8-84c2-6b94b1b8a2d4.png)

**Comment by xandr0s** [comment]
Not replayed for other installations

**Comment by jangrewe** [comment]
I can confirm this, my theonionbox process eventuall goes >10GB memory usage.

![grafik](https://github.com/user-attachments/assets/401c2ced-3307-4723-afd6-09c27eabfcb1)
