### ISSUE TITLE
Tell users to use 'nohup theonionbox &' to continuously run theonionbox

### ISSUE THREAD

**Issue by ghost** [ralphwetzel/theonionbox#48]
Hello, I have discovered that the documentation for this project 'theonionbox' is missing instructions on how users can continuously run theonionbox even after leaving (closing) the SSH session/Console window.

After a bit of digging around, the command 'nohup theonionbox &' works.
The command 'nohup', when appended in front of the startup command 'theonionbox' with a '&' at the end tells the program to ignore additional input and push all output messages from theonionbox to a file called 'nohup.out'. The nohup command seems to work well with theonionbox, and I am able to see the output startup messages when I open the 'nohup.out' file created in the same directory as theonionbox.

Can the 'nohup theonionbox &' command be added to the documentation?
More info about nohup command: https://en.wikipedia.org/wiki/Nohup

<img width="569" alt="nohup-out" src="https://user-images.githubusercontent.com/39027256/40268700-01476960-5bad-11e8-809a-4c967b706863.png">

Besides this, the documentation for this project is awesome and I was able to get theonionbox running with no issues 👍

**Comment by ralphwetzel** [comment]
While your proposal might be suitable to keep your Box running after closing the session, it won't restart after a reboot of your system - thus requiring operator action to bring it up again.

The preferred way to get what you want therefore goes via launching & running The Onion Box as a service (as well called daemon). There is [a whole chapter of the documentation](https://github.com/ralphwetzel/theonionbox#the-onion-box-as-system-service-aka-daemon) dedicated to this topic.

Hope this helps!
