### ISSUE TITLE
ValueError: Unable to resolve tor's user

### ISSUE THREAD

**Issue by yellow444** [ralphwetzel/theonionbox#49]
BOX | While including 'sections/local/local.html' into 'index_page.html': Traceback (most recent call last): File "c:\program files (x86)\python36-32\lib\site-packages\theonionbox\pages\index.html", line 73, in <module> include(file) File "C:\Program Files (x86)\Python36-32\lib\site-packages\bottle.py", line 3386, in _include return self.cache[_name].execute(env['_stdout'], env) File "C:\Program Files (x86)\Python36-32\lib\site-packages\bottle.py", line 3396, in execute eval(self.co, env) File "c:\program files (x86)\python36-32\lib\site-packages\theonionbox\sections\local\local.html", line 122, in <module> {{!standard_row('User', tor.get_user())}} File "C:\Program Files (x86)\Python36-32\lib\site-packages\stem\control.py", line 482, in wrapped return func(self, *args, **kwargs) File "C:\Program Files (x86)\Python36-32\lib\site-packages\stem\control.py", line 1563, in get_user raise ValueError("Unable to resolve tor's user" if self.is_localhost() else "Tor isn't running locally") ValueError: Unable to resolve tor's user

system win 10 x64 
python -V Python 3.6.5
Tor Version 0.3.2.10

https://prnt.sc/jn5ktx
https://prnt.sc/jn5kxq

**Comment by ralphwetzel** [comment]
Thanks for reporting this.
Should now be fixed with [Release v4.2.1](https://github.com/ralphwetzel/theonionbox/tree/v4.2.1).
