### ISSUE TITLE
Traffic stats went away with latest TOR github pull.

### ISSUE THREAD

**Issue by Dozer316** [ralphwetzel/theonionbox#50]
Hello there, many thanks for making this tool available.  Has been working well for months but did a tor update today on Debian Wheezy (complied from source) and the traffic stats for my relay seem broken. 

Getting a ValueError: need more than 1 value to unpack” in the log window and the graph never populates.  Saw some commits to your project a couple of days ago so tried to do an upgrade via pip but that didn't seem to pull down anything new.  Reverted to old stable tor version and traffic stats up again.

Thanks in advance.

**Comment by ralphwetzel** [comment]
Hi!
The latest commits where meant to compensate for [a bug](https://trac.torproject.org/projects/tor/ticket/27039) in the Onionoo protocol - yet they didn't seem to be relevant enough to qualify for a new release. I'll re-consider this.
Can you provide some details, e.g. a line number from the error message, to support debugging of the issue you encountered?

**Comment by Dozer316** [comment]
Will do - not near the machine at the moment but will get back to it tomorrow and get some more verbose info to you.  Many thanks for the response.

**Comment by ralphwetzel** [comment]
As the commit states: This is not related to the Tor version, yet to the "age" of the relay.
_The Box_ interpreted the fact that cached BW data is not available (which is the case for very "young" = recently started nodes) as an issue with the connection to the node - thus suppressing further BW data transmission.
Changed this to just emit a warning indicating the fact & continuing as intended.

Thank you for your support discovering this issue!
I'll pip an updated release shortly.
