### ISSUE TITLE
sqlite dependency isn't listed?

### ISSUE THREAD

**Issue by yurivict** [ralphwetzel/theonionbox#55]
The port user submitted this patch: https://bugs.freebsd.org/bugzilla/attachment.cgi?id=196168&action=diff

I copied the dependencies from setup.py. It looks like sqlite might be missing there.

Thanks!

**Comment by ralphwetzel** [comment]
[sqlite3](https://docs.python.org/2/library/sqlite3.html) is part of the Python Standard Library, since v2.5. It thus should be part of each standard distro - and no dedicated dependency notion necessary.

**Comment by rainlance** [comment]
Running without py-sqlite3 produces the following error on FreeBSD

Traceback (most recent call last):
  File "/usr/local/bin/theonionbox", line 11, in <module>
    load_entry_point('theonionbox==4.2.1', 'console_scripts', 'theonionbox')()
  File "/usr/local/lib/python2.7/site-packages/theonionbox/__main__.py", line 18, in main
    from .theonionbox import main as onion_main
  File "/usr/local/lib/python2.7/site-packages/theonionbox/theonionbox.py", line 1031, in <module>
    from tob.persistor import Storage
  File "/usr/local/lib/python2.7/site-packages/theonionbox/tob/persistor.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

**Comment by yurivict** [comment]
I created a bug record for FreeBSD: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230613

Closing it here.

**Comment by ralphwetzel** [comment]
As consequence to [this comment](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230613#c1) of your bug report I should provide some measures to ensure that the packages demanded specifically for FreeBSD are properly defined.
Can you give me some guidance what is necessary? Is it just `py-sqlite3` ... or something else?

**Comment by yurivict** [comment]
Hi Ralph,

I've already corrected this in the port: https://svnweb.freebsd.org/ports/head/security/theonionbox/Makefile?revision=477126&view=markup#l28

But I don't think that you need to do anything, because people normally install software from ports, and the port is fixed.

Yuri

**Comment by ralphwetzel** [comment]
:ok_hand:
