### ISSUE TITLE
Running with wrong user id on FreeBSD

### ISSUE THREAD

**Issue by rainlance** [ralphwetzel/theonionbox#57]
When The Onion Box is started with /usr/sbin/daemon -u ${theonionbox_user} ${command}, it does run as user theonionbox_user, but the console (tty) username appears in the log file. For example:
Running with permissions of user 'rainlance'
when it should state:
Running with permissions of user '_tor'

**Comment by rainlance** [comment]
Log file from above
       00:04:15.163 The Onion Box: WebInterface to monitor Tor node operations.
        00:04:15.164 Version v4.2.1 (stamp 20180528|203534)
        00:04:15.165 Running on a FreeBSD host.
        00:04:15.166 Running with permissions of user 'rainlance'.
        00:04:15.167 Python version is 2.7.15 (/usr/local/bin/python2.7).
        00:04:15.185 Operating with configuration from '/usr/local/etc/theonionbox/theonionbox'
        00:04:16.322 No temperature sensor information found.
        00:04:16.363 Uptime information located. Expect to get a readout!
        00:04:27.351 Persistance data will be written to '/tmp/.theonionbox.rainlance'.
        00:04:27.776 Ready to listen on http://127.x.x.x:8080/

(username and IP is scrambled)

**Comment by ralphwetzel** [comment]
Technically spoken `The Onion Box` is running with the permissions of the user defined. It yet fails to detect the name of this user correctly.

The fix provided should alter the way of detection thus ensuring proper functionality on *BSD systems (and all others).
Could you please verify?

**Comment by rainlance** [comment]
The fix works. User is now detected correct. Tested on FreeBSD 11.1-RELEASE-p9 amd64.
