### ISSUE TITLE
Data is persisted with wrong name

### ISSUE THREAD

**Issue by rainlance** [ralphwetzel/theonionbox#58]
On FreeBSD when running as user _tor, data is persisted as '/tmp/.theonionbox.rainlance' but should actually be persisted as '/tmp/.theonionbox._tor'.

**Comment by ralphwetzel** [comment]
This is a consequence of #57. Should be fixed as well with the indicated commit.

**Comment by ralphwetzel** [comment]
Fix is confirmed (#57). Closed.
