### ISSUE TITLE
Onionoo key decode issue.

### ISSUE THREAD

**Issue by Dozer316** [ralphwetzel/theonionbox#59]
HI again, latest git pull working great but noticed this in the log window.

[WARN] | 14:28:59 | BOX \| While decoding Onionoo history data: Key 'write_history' not found.
-- | -- | --
[WARN] | 14:28:59 | BOX \| While decoding Onionoo history data: Key 'write_history' not found.

Am I correct to assume that this is just because the relay is young? -  I saw stats in the Consensus Weight and Probabilities area yesterday but I had to delete  the local Tor installs secret key files as I was getting identity has changed messages for Tor in the logs (Updated Tor install) and I'm pretty sure since I did this, the above mentioned log entries have been appearing.   Thanks in advance.

**Comment by ralphwetzel** [comment]
If your assumption is correct, the `warning` should have been gone by now - as some time passed by to generate historical data. Can you confirm?

**Comment by Dozer316** [comment]
It's been running for 24 hours at this stage, and the error is still appearing.  Will continue to monitor and report status.  If there's anything you think I should look at let me know and I'll dig a little further.

**Comment by ralphwetzel** [comment]
If you send me the fingerprint of your relay (by [private mail](https://github.com/ralphwetzel/theonionbox/blob/3c7d4667e1c43ca66656273ef4808c9f5e8a6e22/setup.py#L368)), I can check the Onionoo data directly.

**Comment by ralphwetzel** [comment]
Thank you for sending the fingerprint.
There's - probably due to it's _youth_ - currently no bandwidth data for your relay available in onionoo.
It as well seems to be down currently.

**Comment by Dozer316** [comment]
Many thanks for checking this out - had a couple of network issues earlier which I hope are resolved which may explain the outage.  I will continue to monitor - everything else looks like it's working well.  Thanks again for your help.

**Comment by ralphwetzel** [comment]
To finalize this exchange: There's meanwhile bandwidth data on onionoo for you relay. Thus there should be no more `warning`.
Thank you for operating The Onion Box.

**Comment by Dozer316** [comment]
All good, graphs are being populated now.  

Thanks for all your help.
