### ISSUE TITLE
issues on rpi

### ISSUE THREAD

**Issue by aelray** [ralphwetzel/theonionbox#63]
Hello,
i tried using this tool on my relay on a rpi 1 with debian stretch. I am sshing to my pi and everything seems to work fine, but the theonionbox just immediately closes after startup.

Log with debug info:

        19:43:20.772 The Onion Box: WebInterface to monitor Tor node operations.
        19:43:20.790 Version v4.3.0 (stamp 20181012|201657)
        19:43:20.795 Running on a Linux host.
        19:43:20.800 Running with permissions of user 'pi'.
        19:43:20.806 Python version is 2.7.13 (/home/pi/theonionbox-4.3.0/bin/python).
        19:43:20.812 This seems to be a Python VirtualEnv.
        19:43:20.816 Debug Mode activated from command line.
[DEBUG] 19:43:20.902 theonionbox.py[396]: No configuration file found at
                     '/home/pi/theonionbox-4.3.0/config/theonionbox.cfg'
[DEBUG] 19:43:20.918 theonionbox.py[396]: No configuration file found at
                     '/home/pi/theonionbox-4.3.0/lib/python2.7/site-packages/theonionbox/theonionbox.
                     cfg'
[DEBUG] 19:43:20.932 theonionbox.py[396]: No configuration file found at
                     '/home/pi/theonionbox-4.3.0/lib/python2.7/site-packages/theonionbox/config/theon
                     ionbox.cfg'
        19:43:20.943 No (valid) configuration file found; operating with default settings.
[DEBUG] 19:43:20.998 theonionbox.py[614]: SimpleController Test in Debug & Trace mode:
[DEBUG] 19:43:21.027 theonionbox.py[622]: Trying to connect to Tor @ 127.0.0.1:default.
[DEBUG] 19:43:21.059 theonionbox.py[650]: Successfully connected to Tor @ 127.0.0.1:9051!
[DEBUG] 19:43:21.070 theonionbox.py[651]: This is the response to PROTOCOLINFO request:
[DEBUG] 19:43:21.090 theonionbox.py[659]: 250-PROTOCOLINFO 1
[DEBUG] 19:43:21.100 theonionbox.py[659]: 250-AUTH METHODS=COOKIE,SAFECOOKIE
                     COOKIEFILE="/var/run/tor/control.authcookie"
[DEBUG] 19:43:21.109 theonionbox.py[659]: 250-VERSION Tor="0.2.9.16"
[DEBUG] 19:43:21.118 theonionbox.py[659]: 250 OK
[DEBUG] 19:43:25.035 theonionbox.py[667]: Required packages availability check & version
                     verification:
[DEBUG] 19:43:25.245 theonionbox.py[683]: > apscheduler >=2.1.2, <3.*; python_version<"3.0" required;
                     2.1.2 found @ /home/pi/theonionbox-4.3.0/lib/python2.7/site-packages.
[DEBUG] 19:43:25.425 theonionbox.py[683]: > psutil >=5.4.0 required; 5.5.0 found @
                     /home/pi/theonionbox-4.3.0/lib/python2.7/site-packages.
[DEBUG] 19:43:25.522 theonionbox.py[683]: > futures >=3.2; python_version<"3.0" required; 3.2.0 found
                     @ /home/pi/theonionbox-4.3.0/lib/python2.7/site-packages.
[DEBUG] 19:43:25.675 theonionbox.py[683]: > tzlocal >=1.5 required; 1.5.1 found @
                     /home/pi/theonionbox-4.3.0/lib/python2.7/site-packages.
[DEBUG] 19:43:25.730 theonionbox.py[683]: > bottle >=0.12.13 required; 0.12.16 found @
                     /home/pi/theonionbox-4.3.0/lib/python2.7/site-packages.
[DEBUG] 19:43:27.327 theonionbox.py[683]: > requests >=2.18.0 required; 2.21.0 found @
                     /home/pi/theonionbox-4.3.0/lib/python2.7/site-packages.
[DEBUG] 19:43:27.427 theonionbox.py[683]: > pysocks >=1.6.7 required; 1.6.8 found @
                     /home/pi/theonionbox-4.3.0/lib/python2.7/site-packages.
[DEBUG] 19:43:27.503 theonionbox.py[683]: > urllib3 >=1.22 required; 1.24.1 found @
                     /home/pi/theonionbox-4.3.0/lib/python2.7/site-packages.
[DEBUG] 19:43:27.567 theonionbox.py[683]: > stem >=1.5.4, <=1.6 required; 1.6.0 found @
                     /home/pi/theonionbox-4.3.0/lib/python2.7/site-packages.
        19:43:29.197 Temperature sensor information availabe. Expect to get a chart!
        19:43:29.204 Uptime information located. Expect to get a readout!
        19:43:30.498 Persistance data will be written to '/tmp/.theonionbox.pi'.
[INFO]  19:43:30.646 Next scheduled retry to refresh ONIONOO @ 2019-02-15 05:38:26
        19:43:31.861 Ready to listen on http://127.0.0.1:8080/
        19:43:31.874 Press Ctrl-C to quit!
[DEBUG] 19:43:32.033 theonionbox.py[2873|exit_procedure]: ShutDown Initiated...
[DEBUG] 19:43:32.038 theonionbox.py[2877|exit_procedure]: Shutting down webserver...
[DEBUG] 19:43:32.044 theonionbox.py[2883|exit_procedure]: Shutting down the connection to the
                     proxy...
[DEBUG] 19:43:32.051 theonionbox.py[2900|exit_procedure]: Terminating cron jobs...
[DEBUG] 19:43:32.086 theonionbox.py[2906|exit_procedure]: Terminating onionoo management...
[DEBUG] 19:43:32.092 theonionbox.py[2919|exit_procedure]: List of threads still running (should only
                     be 'MainThread'): MainThread

Any help would be appreciated.

**Comment by ralphwetzel** [comment]
Hi!
My guessing: The port that shall be used - in your case `http://127.0.0.1:8080/` - is not available, blocked by access rights, or in use by another application.

**Comment by aelray** [comment]
thank you!
