### ISSUE TITLE
Error in default config

### ISSUE THREAD

**Issue by svengo** [ralphwetzel/theonionbox#9]
Hi,

I've copied config/theonionbox.cfg to theonionbox.cfg and get the following error:

`[WARN]  18:03:14.683 Configuration: Wrong parameter ''NOTICE'' declared for 'message_level'. Defaulting to 'NOTICE'.`

After changing `message_level = 'NOTICE'` to `message_level = NOTICE` (whithout quotation marks) everything was fine :-)

**Comment by ralphwetzel** [comment]
Thanks for the hint! Will be fixed with the next commit ...
